import { createSlice, PayloadAction } from '@reduxjs/toolkit'
import { RootState } from 'core/store'

// Importing icons for task categories
import UpcomingIcon from '/src/assets/icons/sidebar-upcoming-icon.png'
import WorkIcon from '/src/assets/icons/sidebar-work-icon.png'
import PersonalIcon from '/src/assets/icons/sidebar-personal-icon.png'
import CompletedIcon from '/src/assets/icons/sidebar-completed-icon.png'

// Interface for a Task object
export interface Task {
    userId: string
    id: string
    taskName: string
    taskDescription: string
    category: TaskCategory
    keywords: string[]
    deadline: Date
    completed: boolean
    createdAt: Date
}

// Interface for a TaskCategory object
export interface TaskCategory {
    name: string
    description: string,
    icon: string
}

// Default task categories
export const defaultTaskCategories: TaskCategory[] = [
    {
        name: "Work",
        description: 'Task for Work',
        icon: WorkIcon
    },
    {
        name: "Personal",
        description: 'Task for Personal Life',
        icon: PersonalIcon
    },
]

// Default filter categories
export const defaultFilterCategories: TaskCategory[] = [
    {
        name: "Upcoming",
        description: 'Upcoming Task',
        icon: UpcomingIcon
    },
    {
        name: "Completed",
        description: 'Completed Task',
        icon: CompletedIcon
    },
]

// Initial state for tasks, an empty array
export const initialState: Task[] = []

// Creating a slice for tasks with reducers
const tasksSlice = createSlice({
    name: 'tasks',
    initialState,
    reducers: {
        // Reducer to add a new task
        taskAdded(state, action: PayloadAction<Task>) {
            state.push(action.payload)
        },
        // Reducer to delete a task by ID
        taskDeleted(state, action: PayloadAction<{ taskId: string }>) {
            const existingTask = state.find(task => task.id === action.payload.taskId)
            if (existingTask) {
                state.splice(state.indexOf(existingTask), 1)
            }
        },
        // Reducer to update a task's details
        taskUpdated(state, action: PayloadAction<Task>) {
            const { id, taskName, taskDescription, category, keywords, deadline } = action.payload
            const existingTask = state.find(task => task.id === id)
            if (existingTask) {
                existingTask.taskName = taskName
                existingTask.taskDescription = taskDescription
            }
        },
        // Reducer to update a task's completion status
        taskCompletionUpdate(state, action: PayloadAction<{ taskId: string, status: boolean }>) {
            const existingTask = state.find(task => task.id === action.payload.taskId)
            if (existingTask) existingTask.completed = action.payload.status
        },
        // Reducer to update a task's ID
        taskIdUpdated(state, action: PayloadAction<{ localId: string, serverId: string }>) {
            const existingTask = state.find(task => task.id === action.payload.localId)
            if (existingTask) existingTask.id = action.payload.serverId
        }
    }
})

// Exporting actions generated by createSlice
export const { taskAdded, taskCompletionUpdate, taskIdUpdated, taskUpdated, taskDeleted } = tasksSlice.actions

// Selector to get all tasks from the state
export const selectAllTasks = (state: RootState) => state.tasks

// Selector to get a task by ID from the state
export const selectTaskById = (state: RootState, id: string) => state.tasks.find(task => task.id === id)

// Export the generated reducer function
export default tasksSlice.reducer